# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 04:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ptc', '0002_profesor_passw'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plaza',
            fields=[
                ('id_pla', models.AutoField(primary_key=True, serialize=False)),
                ('plaza_pla', models.CharField(max_length=255)),
            ],
        ),
    ]
