# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-03 17:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ptc', '0005_eval_materia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acedemia',
            fields=[
                ('id_ace', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_aca', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id_dep', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_dep', models.CharField(max_length=255)),
            ],
        ),
    ]
