# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-03 18:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ptc', '0007_auto_20171203_1723'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id_cur', models.AutoField(primary_key=True, serialize=False)),
                ('actividad_cur', models.CharField(max_length=255)),
                ('avance_cur', models.CharField(max_length=255)),
                ('evidencia_cur', models.CharField(max_length=500)),
                ('materia_cur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ptc.Materias')),
            ],
        ),
    ]
