# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-03 21:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ptc', '0009_auto_20171203_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='evidencia_cur',
            field=models.CharField(max_length=500),
        ),
    ]
