# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-24 18:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ptc', '0011_talleres'),
    ]

    operations = [
        migrations.CreateModel(
            name='Taller_Educacion',
            fields=[
                ('id_tae', models.AutoField(primary_key=True, serialize=False)),
                ('taller_tae', models.CharField(max_length=255)),
                ('horas_tae', models.FloatField()),
                ('profesores_tae', models.TextField()),
                ('evidencia_tae', models.CharField(max_length=500)),
                ('year_tae', models.IntegerField()),
                ('profesor_tae', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ptc.Profesor')),
            ],
        ),
    ]
