# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-24 20:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ptc', '0012_taller_educacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='taller_educacion',
            name='status_tae',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
