# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-25 20:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ptc', '0013_taller_educacion_status_tae'),
    ]

    operations = [
        migrations.CreateModel(
            name='Taller_EduAbierta',
            fields=[
                ('id_tea', models.AutoField(primary_key=True, serialize=False)),
                ('taller_tea', models.CharField(max_length=255)),
                ('horas_tae', models.FloatField()),
                ('profesores_tea', models.TextField()),
                ('evidencia_tea', models.CharField(max_length=500)),
                ('year_tea', models.IntegerField()),
                ('status_tea', models.CharField(max_length=255, null=True)),
                ('profesor_tea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ptc.Profesor')),
            ],
        ),
    ]
