# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-25 20:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ptc', '0014_taller_eduabierta'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taller_eduabierta',
            old_name='horas_tae',
            new_name='horas_tea',
        ),
    ]
