# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-05 22:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ptc', '0016_material_didactico'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proceso_Titulacion',
            fields=[
                ('id_prt', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_prt', models.CharField(max_length=255)),
                ('nivel_prt', models.CharField(max_length=255)),
                ('titulo_prt', models.CharField(max_length=255)),
                ('evidencia_prt', models.CharField(max_length=500)),
                ('year_prt', models.IntegerField()),
                ('profesor_prt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ptc.Profesor')),
            ],
        ),
    ]
