# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-14 15:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ptc', '0017_proceso_titulacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto_Investigacion',
            fields=[
                ('id_pri', models.AutoField(primary_key=True, serialize=False)),
                ('financiamiento_pri', models.CharField(max_length=255)),
                ('participacion_pri', models.CharField(max_length=255)),
                ('titulo_inv_pri', models.CharField(max_length=255)),
                ('responsable_pri', models.CharField(max_length=255)),
                ('profesores_pri', models.CharField(max_length=255)),
                ('producto_pri', models.CharField(max_length=255)),
                ('subproducto_pri', models.CharField(max_length=255)),
                ('titulo_prod_pri', models.CharField(max_length=255)),
                ('status_prod_pri', models.CharField(max_length=255)),
                ('comite_pri', models.CharField(max_length=255)),
                ('evidencia_pri', models.CharField(max_length=500)),
                ('year_pri', models.IntegerField()),
                ('profesor_pri', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ptc.Profesor')),
            ],
        ),
    ]
