# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-14 16:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ptc', '0018_proyecto_investigacion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proyecto_investigacion',
            old_name='status_prod_pri',
            new_name='status_pri',
        ),
    ]
